# Generated by Django 4.1.1 on 2024-01-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_alter_videos_urlstring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='urlstring',
        ),
        migrations.AddField(
            model_name='videos',
            name='url',
            field=models.URLField(default='url'),
        ),
    ]
