# Generated by Django 4.1.1 on 2024-01-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_videos_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='spanish_text',
            field=models.TextField(default='texto por defecto'),
            preserve_default=False,
        ),
    ]
