# Generated by Django 4.1.1 on 2024-01-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_videos_spanish_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='speech',
            field=models.FileField(default='', upload_to='speech'),
        ),
    ]
