# Generated by Django 4.1.1 on 2024-01-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_videos_speech'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='thumbnail',
            field=models.FileField(default='', upload_to='thumbnail'),
        ),
    ]
